name: SonarQube Scan

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Scan with SonarQube
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    
    - name: SonarQube Scan
      run: |
        mvn clean verify sonar:sonar -Psonar\
          -Dsonar.projectKey=your-project-key \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.qualitygate.wait=true
    
    - name: Quality Gate Check
      run: |
        if [[ $(cat .sonarqube/out/.sonar/report-task.txt | grep -o 'status=FAILED') ]]; then
          echo "Quality Gate failed: Pull request cannot be merged to master";
          exit 1;
        fi
